### ISSUE TITLE
No Connection

### ISSUE THREAD

**Issue by robhein** [segler-alex/RadioDroid#1248]
No Connection to Radiostation

**Comment by morckx** [comment]
Should be working again.

**Comment by apuser31** [comment]
Not working for me yet: Issue #1247 has been closed but I am still having the same problem.

**Comment by wintherd** [comment]
Thanks, the connection to radio-browser.info is now working for me.  I also upgraded my LetsEncrypt certificates which may be a factor in gettings things working again on older versions of Android.
