### ISSUE TITLE
Feature Request: Continue streaming after connection loss

### ISSUE THREAD

**Issue by phixx** [segler-alex/RadioDroid#131]
I am not sure if this is implemented to some extend, but, at least for me, the player could retry playback more aggressively.

I am using this nice app over LTE in my car. Playback is dropped (naturally) when I enter a tunnel, but it does not continue after getting network back. At least not fast enough to keep me from restarting manually.

**Comment by Wikinaut** [comment]
:+1:

**Comment by muto4013** [comment]
nothing ? It would be a nice feature to have, especial if you use RD mobile or suffer like me from disconnects from provider.

**Comment by Cormak** [comment]
@muto4013 @phixx @segler-alex this might have been resolved with https://github.com/segler-alex/RadioDroid/releases/tag/0.36 according to the changelog for that release.

**Comment by werman** [comment]
It is partially resolved but there are still issues when having unstable connection. Sometimes it's faster to pause and resume playback than wait until it resumes by itself.

**Comment by morckx** [comment]
Still not resolved for me. In particular when I roam between different wifi networks, streaming stops each time and is not continued in time.

**Comment by morckx** [comment]
Yes, thanks. Also setting the reconnection delay to a time that is at most needed for connecting to the new access point (2000ms in my case) seems to help. Reacting to connectivity broadcasts could be a better options, but haven't had a look at the source code.

**Comment by werman** [comment]
Yeah, reacting to broadcast is a good idea, I forgot about it last time I changed relevant logic.

**Comment by morckx** [comment]
I've experimented a little with a  receiver for `ConnectivityManager.CONNECTIVITY_ACTION` intents that 'prepares` the audio source again when the connectivity is regained. In my tests at home this works very well with switching networks off and on. Will test this also on the road with read dead spots, after Christmas...
